# NumPy 从数值范围创建数组

这一章节我们将学习如何从 **数值范围** 创建数组。

### numpy.arange

numpy 包中的使用 arange 函数创建数值范围并返回 ndarray 对象，函数格式如下：

```
numpy.arange(start, stop, step, dtype)
```

根据 start 与 stop 指定的范围以及 step 设定的步长，生成一个 ndarray。

参数说明：

| 参数    | 描述                                                         |
| :------ | :----------------------------------------------------------- |
| `start` | 起始值，默认为`0`                                            |
| `stop`  | 终止值（不包含）                                             |
| `step`  | 步长，默认为`1`                                              |
| `dtype` | 返回`ndarray`的数据类型，如果没有提供，则会使用输入数据的类型。 |

### 实例

生成 0 到 5 的数组:

In [1]:
import numpy as np

In [3]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

设置返回类型位 float

In [5]:
# 设置了 dtype 参数
x = np.arange(5, dtype=float)
x

array([0., 1., 2., 3., 4.])

设置了起始值、终止值及步长：

In [7]:
x = np.arange(10, 20, 2)
x

array([10, 12, 14, 16, 18])

### numpy.linspace

numpy.linspace 函数用于 **创建** 一个 **一维数组**，数组是一个 **等差数列** 构成的，格式如下：

```
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```

参数说明：

| 参数       | 描述                                                         |
| :--------- | :----------------------------------------------------------- |
| `start`    | 序列的起始值                                                 |
| `stop`     | 序列的终止值，如果`endpoint`为`true`，该值包含于数列中       |
| `num`      | 要生成的等步长的样本数量，默认为`50`                         |
| `endpoint` | 该值为 `true` 时，数列中包含`stop`值，反之不包含，默认是True。 |
| `retstep`  | 如果为 True 时，生成的数组中会显示间距，反之不显示。         |
| `dtype`    | `ndarray` 的数据类型                                         |

以下实例用到三个参数，设置起始点为 1 ，终止点为 10，数列个数为 10。

In [8]:
a = np.linspace(1, 10, 10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

设置元素全部是 1 的等差数列：

In [10]:
a = np.linspace(1, 1, 10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

将 endpoint 设为 false，不包含终止值：

In [13]:
a = np.linspace(10, 20, 5, endpoint=False)
a

array([10., 12., 14., 16., 18.])

如果将 `endpoint` 设为 `true`，则会包含 20。

In [15]:
a = np.linspace(1, 10, 10,endpoint=True)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

以下实例设置间距

In [16]:
a = np.linspace(1, 10, 10, retstep=True)
a

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)

扩展例子

In [19]:
a = np.linspace(1, 10, 10).reshape(5, 2)
a

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

### numpy.logspace

numpy.logspace 函数用于 **创建** 一个 **等比数列**。格式如下：

```
np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
```

base 参数意思是取对数的时候 log 的下标。

| 参数       | 描述                                                         |
| :--------- | :----------------------------------------------------------- |
| `start`    | 序列的起始值为：base ** start                                |
| `stop`     | 序列的终止值为：base ** stop。如果`endpoint`为`true`，该值包含于数列中 |
| `num`      | 要生成的等步长的样本数量，默认为`50`                         |
| `endpoint` | 该值为 `true` 时，数列中中包含`stop`值，反之不包含，默认是True。 |
| `base`     | 对数 log 的底数。默认的底数为 10            |
| `dtype`    | `ndarray` 的数据类型                                         |

#### 实例

In [21]:
# 默认底数为 10
a = np.logspace(1.0, 2.0, num =10) # 10**1.1, 10**1.2..., 10**2
a

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

#### 实例

将对数的底数设置为 2：

In [23]:
a = np.logspace(0, 9, 10, base=2) # 2**1, 2**2..., 2**10
a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])