# Numpy 的核心 array 对象以及创建 array 的方法

##### array 对象的背景：

- `Numpy` 的 **核心数据结构**，就叫做 `array` 就是 **数组**，`array` 对象可以是 **一维数组**，**也可以是多维数组**；
- `Python` 的 `List` 也可以实现相同的功能，但是 `array` 比 `List` 的优点在于 **性能好**、**包含数组元数据信息**、**大量的便捷函数**；
- `Numpy` 成为事实上的 `Scipy`、`Pandas`、`Scikit-Learn`、`Tensorflow`、`PaddlePaddle` 等框架的 **“通用底层语言”**
- `Numpy` 的 `array` 和 `Python` 的 `List` 的一个区别，是它 **元素必须都是同一种数据类型**，比如都是数字 `int` 类型，这也是 `Numpy` 高性能的一个原因；

##### array 本身的属性

- `shape` : 返回一个元组，表示 `array` 的维度
- `ndim` : 一个数字，表示 `array` 的维度的数目
- `size` : 一个数字，表示 `array` 中所有数据元素的数目
- `dtype` : `array` 中元素的数据类型

##### 创建 array 的方法

- 从 `Python` 的列表 `List` 和嵌套列表创建 `array`
- 使用预定函数 `arange`、`ones/ones_like`【**数组全为 1**】、`zeros/zeros_like`【**数组全为 0**】、`empty/empty_like`【**数组全为空**】、`full/full_like`【**数组全为指定数值**】、`eye`【**矩阵对角线全为 1**】 等函数创建
- **生成随机数** 的 `np.random` 模块构建

##### `array` 本身支持的大量操作和函数

- 直接 **逐元素的加减乘除** 等算数操作

- 更好用的 **面向多维的数组索引**
- 求 `sum/mean` 等 **聚合函数**
- 线性代数函数，比如 **求解逆矩阵**、**求解方程组**

## 1. 使用 Python 的 List 和嵌套 List 创建一维的 array 和二维的 array

In [1]:
import numpy as np

In [2]:
# 创建一个以为数组，也就是 Python 的单元素 List
x = np.array([1,2,3,4,5,6,7,8])

In [3]:
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
# 创建一个二维数组，也就是 Python 的嵌套 List
x2 = np.array(
    [
        [1,2,3,4],
        [5,6,7,8]
    ]
)

In [10]:
x2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## 2. 探索数组 array 的属性

#### 2.1 维度

In [11]:
x.shape

(8,)

In [12]:
x2.shape

(2, 4)

#### 2.2 维度数目

In [13]:
x.ndim

1

In [14]:
x2.ndim

2

#### 2.3 数据元素数目

In [15]:
x.size

8

In [16]:
x2.size

8

#### 2.4 数据类型

In [17]:
x.dtype

dtype('int64')

In [18]:
x2.dtype

dtype('int64')

## 3. 创建 array 的便捷函数

##### 使用 arange 创建数字序列 【类似 Python 的 range 函数】

`arange([start,]stop[,step],dype=None)` 

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(2,10,2) # 从 2 开始到 10 结束，步长为 2

array([2, 4, 6, 8])

##### 使用 ones 创建全是 1 的数组

`np.ones(shape,dtype=None,order="C")`

shape : int or tuple of ints Shape of the new array, e.g.,`(2,3)` or `2`


In [22]:
np.ones(10) # 一维

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.ones((2,3)) # 两行三列

array([[1., 1., 1.],
       [1., 1., 1.]])

使用 ones_like 创建形状相同的数组

`ones_like(a,dtype=float,order="C")`

In [26]:
np.ones_like(x) # x 是一维的，仿照 x 创建的数组

array([1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
np.ones_like(x2) # x2 是二维的，仿照 x2 创建的数组

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

##### 使用 zeros 创建全是 0 的数组

`np.zeros(shape,dtype=None,order="C")`

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

##### 使用 zeros_like 创建形状相同的 0 数组 【同上 `ones_like`】

`np.zeros_like(a,dtype=None)`

In [31]:
np.zeros_like(x)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
np.zeros_like(x2)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

##### 使用 empty 创建全是 0 的数组【未初始化的】

`empty(shape,dtype=float,order="C")`

注意：数据是未初始化的，里面的值可能是随机值不要用

In [33]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.empty((2,4))

array([[4.68473395e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.20428116e+223,
        3.29160367e-318]])

##### 使用 empty_like 创建形状相同的数组

`empty_like(prototype,dtype=None)`

In [35]:
np.empty_like(x)

array([     94820070742976,                   0,                   0,
                         0,                   0,                   0,
       7954892334483857255,              666228])

In [36]:
np.empty_like(x2)

array([[94820070742976,              0,   489626271845,   493921239151],
       [  463856468063,   459561500777,   171798691941,   176093659256]])

##### 使用 full 创建指定值的数组

`np.full(shape,fill_value,dtype=None,order="C")`

In [37]:
np.full(10,666)

array([666, 666, 666, 666, 666, 666, 666, 666, 666, 666])

In [38]:
np.full((2,4),333)

array([[333, 333, 333, 333],
       [333, 333, 333, 333]])

##### 使用 full_like 创建形状相同的数组

`np.full_like(a,fill_value,dtype=None)`

In [39]:
np.full_like(x,666)

array([666, 666, 666, 666, 666, 666, 666, 666])

In [40]:
np.full_like(x2,666)

array([[666, 666, 666, 666],
       [666, 666, 666, 666]])

使用 random 模块生成随机数的数组

`randn(d0,d1,...,dn)`

In [41]:
np.random.randn() # 一个随机数

1.1052141589620574

In [42]:
np.random.randn(3) # 三行的一维数组

array([-0.33551328, -0.2888917 , -0.73527532])

In [43]:
np.random.randn(3,2) # 三行两列的二维数组

array([[ 0.02996096,  0.90889268],
       [ 1.15428802, -1.47112441],
       [-2.15848369,  1.35723324]])

In [44]:
np.random.randn(3,2,4) # 三块，两行四列

array([[[ 0.33107079, -1.04353086, -0.3064977 ,  0.31906292],
        [-1.18198374,  2.17332668,  0.08745776, -1.06653117]],

       [[-0.05823263,  1.48884225,  0.82187316, -0.1621461 ],
        [ 1.13434633, -0.68631212,  1.23923138,  0.22738124]],

       [[ 0.16228155, -0.31755364, -0.29193169,  0.49608777],
        [ 0.06364697,  0.74458333, -1.1110425 ,  0.27380708]]])

## 3. 创建 array 的便捷函数

这些操作如果用 Python 实现需要写很多 for 循环，用 numpy 数组则很容易实现

In [51]:
A = np.arange(10).reshape(2,5) # 将一维数组 -> 二维数组

In [52]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
A.shape

(2, 5)

In [55]:
A + 1 # 将数组中的数都 + 1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [56]:
A * 3 # 将数组中的数都 × 3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])

In [57]:
np.sin(A) # 求数组每个数的 sin

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [58]:
np.exp(A) # 求e的数组中数字次方

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

In [59]:
B = np.random.randn(2,5)

In [60]:
B

array([[-1.42250509, -0.87316486, -0.89578882,  1.31997015, -0.3183106 ],
       [-0.55255982, -1.16399146, -1.46618265, -1.87743498, -1.53794725]])

In [61]:
A + B # 对应元素相加

array([[-1.42250509,  0.12683514,  1.10421118,  4.31997015,  3.6816894 ],
       [ 4.44744018,  4.83600854,  5.53381735,  6.12256502,  7.46205275]])

In [62]:
A - B # 对应元素相减

array([[ 1.42250509,  1.87316486,  2.89578882,  1.68002985,  4.3183106 ],
       [ 5.55255982,  7.16399146,  8.46618265,  9.87743498, 10.53794725]])